name: Lint Python code with Pycodestyle

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Pycodestyle
      run: |
        pip install pycodestyle
        
    - name: Lint Python files with Pycodestyle
      run: |
        pycodestyle .
